### ISSUE TITLE
想咨询下golang 目前能满足海康威视的所有业务不

### ISSUE THREAD

**Issue by Jiachang-Cai** [Modestying/HCNetSDK_golang#1]
这边主要的语言为golang 目前官网没有golang sdk 不知道是否 还是使用Java 等

**Comment by Modestying** [comment]
海康的二次开发目前还是以C++为主，相关SDK功能代码封装后无论是用来做PC端软件还是服务端都可以直接用，显著减少开发时间
JAVA个人不太熟悉，不太了解相关开发

至于golang目前能否满足所有业务，就我个人目前接触来看，常用的SDK函数是可以满足的
