### ISSUE TITLE
想询问一下， 一直显示这个报错cannot find -lHCNetSDK

### ISSUE THREAD

**Issue by liuwangg** [Modestying/HCNetSDK_golang#2]
# runtime/cgo
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lHCNetSDK
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:7: windows] Error 2

**Comment by Modestying** [comment]
已经更新了，可以再试下，`winodows`平台请根据`internal/Device/HKDevice.go`中提示修改变量类型

**Comment by liuwangg** [comment]
thank u!!!
