### ISSUE TITLE
报错 HKDevice.go: invalid #cgo line: #cgo LDFLAGS 需要根据不同的平台修改 hcnetsdk（linux) / HCNETSDK(Windows)

### ISSUE THREAD

**Issue by Yancy0220** [Modestying/HCNetSDK_golang#3]
/*
#cgo CFLAGS:  -I../../include
#cgo LDFLAGS: -L$../../build  -lHCCore -lhpr -lhcnetsdk
#include <stdio.h>
#include <stdlib.h>
#include "HCNetSDK.h"
extern void AlarmCallBack(LONG lCommand, NET_DVR_ALARMER *pAlarmer, char *pAlarmInfo, DWORD dwBufLen, void* pUser);
*/

也没问题啊，请指教

**Comment by Modestying** [comment]
用git bash 终端make 命令编译，然后终端运行exe

**Comment by Yancy0220** [comment]
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/0e35d03e-0e8c-42a0-ba4e-88acb7c58568">

是不是需要说明一下，运行时把这个去掉

**Comment by Modestying** [comment]
> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/44826486/352436186-0e35d03e-0e8c-42a0-ba4e-88acb7c58568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzk2NDYsIm5iZiI6MTcyMTk3OTM0NiwicGF0aCI6Ii80NDgyNjQ4Ni8zNTI0MzYxODYtMGUzNWQwM2UtMGU4Yy00MmEwLWJhNGUtODhhY2I3YzU4NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNDEyMGU2YWM1YWNjYTM2NDA2NzFjYzM5MmExMjY4ZDMzMWJiNTMzOWJlYjIxYjc4MWZiN2I4ODQyMTk5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OducGtoQHwuNLyTqm7ClSt78JQG9WC7MU6RJQKa8HY">
> 是不是需要说明一下，运行时把这个去掉

晚上回去我看下，时间有点久了
